## Numpy Array Operation

In [2]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing ",arr[2:7]) #arr[start,end]
print("With Step ",arr[1:8:2]) #arr[start,end,step]
print("Negative indexing ", arr[-3]) #return from the last


Basic Slicing  [3 4 5 6 7]
With Step  [2 4 6 8]
Negative indexing  8


In [7]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [6,7,8]])

print("Specific element ",arr2[1,2]) #arr2[row,index]
print("Entire row: ",arr2[1]) #row target
print("Entire Col: ",arr2[:,2]) #arr2[:,col_index]  : -> means target column



Specific element  6
Entire row:  [4 5 6]
Entire Col:  [3 6 8]


### Sorting

In [ ]:
unsort = np.array([4,6,7,3,7,1,0,8,9])
print("Sorted Array ",np.sort(unsort))

arr = np.array([[3,1],[5,2],[2,3]])
print("Sorted 2D array by column ",np.sort(arr,axis = 0)) # axis 0 all array sorted column wise
# [[2 1]
#  [3 2]
#  [5 3]]

print("Sorted 2D array by column ",np.sort(arr,axis = 1)) # axis 1 all array sorted row wise
# [[1 3]
#  [2 5]
#  [2 3]]


Sorted Array  [0 1 3 4 6 7 7 8 9]
Sorted 2D array by column  [[2 1]
 [3 2]
 [5 3]]
Sorted 2D array by column  [[1 3]
 [2 5]
 [2 3]]


## Filter

In [4]:
num = np.array([1,2,3,4,5,6,7,8,9,10])

even_num = num[num%2==0]
print("even numbers",even_num)

even numbers [ 2  4  6  8 10]


## Filter With mask

In [15]:
mask = num>5  # [f,f,f,f,f,t,t,t,t,t]  -> boolean mask
print("Numbers greater than 5",num[mask]) # return num whose value is true

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy Indexing  vs  np.where()

In [ ]:
indices = [0,2,4]
print(num[indices])  # return the value at index which is in indices

where_res = np.where(num>5) 
print(where_res)
print("Np where ",num[where_res])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np where  [ 6  7  8  9 10]


In [ ]:
con_arr = np.where(num>5,"true","false")
# if(num>5){
#     store true
# }else{
#     store false
# }
print(con_arr)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# com = arr1+arr2
com = np.concatenate((arr2,arr1))
print(com)

[4 5 6 1 2 3]


### Array compatibility

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,5])

print("Compatibility Shape ", a.shape == b.shape) # Check that dimension of both array is equal or not

Compatibility Shape  True


In [ ]:
org = np.array([[1,2],[3,4]])

new_row = np.array([5,6])
new = np.vstack((org,new_row)) # Add new Row and create duplicate array

print(org)
print(new)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
newcol = np.array([[7],[8]])
newarr = np.hstack((org,newcol)) # Add new Column
print(org)
print(newarr)

[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1,2,3,4,5])
dele = np.delete(arr,2) # return array after deleting the particular index value

print(arr)
print(dele) 

[1 2 3 4 5]
[1 2 4 5]


In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np. array( [
[1, 150000, 180000, 220000, 250000], # Paradise Biryani
[2, 120000, 140000, 160000, 190000], # Beijing Bites
[3, 200000, 230000, 260000, 300000], # Pizza Hub
[4, 180000, 210000, 240000, 270000], # Burger Point
[5, 160000, 185000, 205000, 230000]  # Chai Point

])

print("=====Zomato sales Analysis=======")

print("\n Slaes data shape",sales_data.shape)
print("\n sample data for 1st 3 restaurant\n", sales_data[0:3]) # or sales_data[:3]


=====Zomato sales Analysis=======

 Slaes data shape (5, 5)

 sample data for 1st 3 restaurant
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
# Total Sales per year

print(np.sum(sales_data,axis=0))

# Yearly Total
yt = np.sum(sales_data[:,1:],axis=0)
print(yt)

total = np.sum(yt,axis=0) 
print(total)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
4080000


In [25]:
# Minimum Sales per Restaurant
minsales = np.min(sales_data[:,1:],axis=1)
print(minsales)

# Maximum sales per year
maxsales = np.max(sales_data[:,1:],axis=0)
print(maxsales)

# Average sales per Restaurant
avg = np.mean(sales_data[:,1:],axis=1)
print(avg)

[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]


In [26]:
# Cummulative sum
cumsum = np.cumsum(sales_data[:,1:],axis=1)
print(cumsum)

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [30]:
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([9,8,7,6,5])

print("Vector Addition ",vector1+vector2)
print("\n Vector Multiplication ",vector1*vector2)
print("\n Dot Product",np.dot(vector1,vector2))

angle = np.arccos(np.dot(vector1,vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2)))
print(angle)

deg = np.degrees(angle)
print(deg)


Vector Addition  [10 10 10 10 10]

 Vector Multiplication  [ 9 16 21 24 25]

 Dot Product 95
0.6398578707052999
36.661155479641195


In [33]:
res = np.array(['biryani','chinese','pizza','burger','cafe'])
vectorize_upper = np.vectorize(str.upper)
print(vectorize_upper(res))

['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


In [35]:
#broadcast

mon_avg = sales_data[:,1:] / 12

print(mon_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
