### Creating Array from numpy

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,6])
print(arr1)

[1 2 3 4 6]


In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [4]:

pylist = [1,2,3]
print("python list multiplication",pylist*2)

np_arr = np.array([1,2,3]) #Element wise multiplication
print("py numpy multiplication",np_arr*2)



python list multiplication [1, 2, 3, 1, 2, 3]
py numpy multiplication [2 4 6]


In [8]:

import time
start = time.time()
list = [i*2 for i in range(1000000)]
print(" List operation time:",time.time()-start)


start = time.time()
nparr = np.arange(1000000)*2
print(" Numpy operation time:",time.time()-start)

 List operation time: 0.10985660552978516
 Numpy operation time: 0.012615203857421875


### creating array from scratch

In [ ]:
zeros = np.zeros((3,4)) #(row,col)
print(zeros)

ones = np.ones((2,3))
print(ones)

full = np.full((2,2),7) #((row,col),value)
print("full Array: \n",full)

ran = np.random.random((2,3))
print("random array: \n",ran)

sequence = np.arange(0,9,1) #(start, end, gap between values)
print("sequence array: \n",sequence)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
full Array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.01552651 0.0547635  0.49995001]
 [0.62047059 0.18297237 0.48192469]]
sequence array: 
 [0 1 2 3 4 5 6 7 8]


### Vector, Matrix and Tensor

In [17]:
vector = np.array([1,2,3])
print("vector : ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix : ",matrix)

tensor = np.array([[[1,2] , [3,4]],
                   [[5,6] , [7,8]]])
print("tensor : ",tensor)

vector :  [1 2 3]
matrix :  [[1 2 3]
 [4 5 6]]
tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [19]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ", arr.size)
print("Dtype ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Dtype  int64


### Array Reshaping

In [21]:
arr = np.arange(12)
print("original Array: ", arr)

reshape = arr.reshape((3,4))
print("\n Reshaped array ",reshape)

flatten = reshape.flatten() #this return original array
print("\n flattened array ",flatten)

raveled = reshape.ravel() # this return original array
print("\n raveled array ", raveled)

transpose = reshape.T
print("\n transposed array ",transpose)


original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
